[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]
aptPkgs = ["libmagic1"]

[phases.install]
cmds = [
  "pip install -r backend/requirements.txt"
]

[start]
cmd = "cd backend && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
LANG = "C.UTF-8"

[variables]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
