[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]
aptPkgs = ["libmagic1"]

[start]
cmd = "python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
LANG = "C.UTF-8"

[variables]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
