name: Deploy Backend to Cloud Run

on:
  push:
    branches: [ master, main ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'backend/**'
    types: [ closed ]

jobs:
  deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
        
    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
        
    - name: Configure Docker for Google Cloud
      run: |
        gcloud auth configure-docker
        gcloud auth configure-docker us-central1-docker.pkg.dev
      
    - name: Build and Deploy to Cloud Run
      run: |
        # Get the project ID from gcloud config
        PROJECT_ID=$(gcloud config get-value project)
        
        # Debug: List files in backend directory to verify requirements.txt exists
        echo "Files in backend directory:"
        ls -la backend/
        
        # Verify requirements.txt exists
        if [ ! -f "backend/requirements.txt" ]; then
          echo "ERROR: requirements.txt not found in backend directory"
          exit 1
        fi
        
        # Build the Docker image with verbose output
        echo "Building Docker image..."
        docker build -t us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/documind-backend ./backend --progress=plain
        
        # Push the image to Artifact Registry
        echo "Pushing Docker image..."
        docker push us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/documind-backend
        
        # Deploy to Cloud Run using the pushed image
        echo "Deploying to Cloud Run..."
        gcloud run deploy documind-backend \
          --image us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/documind-backend \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars="REDIS_HOST=${{ secrets.REDIS_HOST }},REDIS_PORT=${{ secrets.REDIS_PORT }},REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }},REDIS_SSL=true,REDIS_REQUIRED=true,OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }},ENVIRONMENT=production,FRONTEND_URL=https://documind-ruby.vercel.app,CORS_ALLOW_ALL=true" \
          --memory=1Gi \
          --cpu=1 \
          --max-instances=10 \
          --timeout=300
          
    - name: Get service URL
      run: |
        SERVICE_URL=$(gcloud run services describe documind-backend --region=us-central1 --format='value(status.url)')
        echo "Backend deployed to: $SERVICE_URL"
        echo "SERVICE_URL=$SERVICE_URL" >> $GITHUB_OUTPUT
        
    - name: Test deployment
      run: |
        SERVICE_URL=$(gcloud run services describe documind-backend --region=us-central1 --format='value(status.url)')
        curl -f "$SERVICE_URL/health" || exit 1
        echo "✅ Backend deployment successful and healthy"
