name: Deploy Backend to Cloud Run

on:
  push:
    branches: [ master, main ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'backend/**'
    types: [ closed ]

jobs:
  deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true
        
    - name: Configure Docker for Google Cloud
      run: gcloud auth configure-docker
      
    - name: Deploy to Cloud Run
      run: |
        cd backend
        gcloud run deploy documind-backend \
          --source . \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars="REDIS_HOST=${{ secrets.REDIS_HOST }},REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" \
          --memory=1Gi \
          --cpu=1 \
          --max-instances=10 \
          --timeout=300
          
    - name: Get service URL
      run: |
        SERVICE_URL=$(gcloud run services describe documind-backend --region=us-central1 --format='value(status.url)')
        echo "Backend deployed to: $SERVICE_URL"
        echo "SERVICE_URL=$SERVICE_URL" >> $GITHUB_OUTPUT
        
    - name: Test deployment
      run: |
        SERVICE_URL=$(gcloud run services describe documind-backend --region=us-central1 --format='value(status.url)')
        curl -f "$SERVICE_URL/health" || exit 1
        echo "✅ Backend deployment successful and healthy"
